package com.example.core_ui.constant

object SharedUiLogicConstant {
    val COMING_VISITS_INFORMATION_WINDOW_STATUS_LIST = listOf(
        COMING_STATUS_COMING,
        COMING_STATUS_NOT_COMING,
        COMING_STATUS_SOON
    )
    const val COMING_STATUS_COMING = "Проведено"
    const val COMING_STATUS_NOT_COMING = "Отменено"
    const val COMING_STATUS_SOON = "Назначено"
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_STATUS_VISIT = "Назначено"
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_NAME_VISIT = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_PAY_STATUS = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_INFO_VISIT = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_VISIT_DATE_COMING = ""
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_NAME = ""
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DESCRIPTION = ""
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_SELECTED_IMAGE_INDEX = 0
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_SELECTED_IMAGE_MINUS_INDEX = 1
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DOCS_LIST_REMOVE_INDEX = 1
    const val DOCUMENT_INFORMATION_WINDOW_ADD_IMAGE_ICON_SIZE = 50
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_SPACER_HEIGHT = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_SIZE = 80
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_PADDING_HORIZONTAL = 4
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_CLIP = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_BOX_SIZE = 80
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_BOX_CLIP = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_SIZE = 30
    const val DOCUMENT_INFORMATION_WINDOW_SPACER_IMAGE_TO_DOCS_INFO_HEIGHT = 16
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DOCS_LIST_ADD_INDEX = 1
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_DEBT = "Долг"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_PAY_SOON = "Оплата в след.визит"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_PAYED = "Хватает для оплаты"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_NOT_PAYED = "Не Хватает для оплаты"
    const val CHILD_CARD_INITIAL_FULL_NAME_INDEX = 2
    const val CHILD_CARD_INITIAL_PARTS_INDEX_FIRST_NAME = 0
    const val CHILD_CARD_INITIAL_PARTS_INDEX_LAST_NAME = 1
    const val CHILD_CARD_INITIAL_PARTS_INDEX_TAKE_INDEX = 2
    const val CHILD_CARD_DEFAULT_VALUE_PAY_STATUS = ""
    const val GET_DATE_TEXT_INPUT_DATE_FORMAT = "%02d.%02d.%d"
    const val HEADER_DEFAULT_VALUE_INFO_SELECTION = ""
    const val FOOTER_ITEM_DEFAULT_VALUE_PADDING_START = 1
    const val FOOTER_ITEM_DEFAULT_VALUE_PADDING_END = 3
    const val FOOTER_SELECTED_INDEX_DEFAULT_VALUE = 0
    const val TIME_HELPER_DEFAULT_VALUE_HOUR = 12
    const val TIME_HELPER_DEFAULT_VALUE_MINUTE = 0
    const val INFORMATION_INITIAL_FIRST_NAME_INDEX = 0
    const val INFORMATION_INITIAL_SECOND_NAME_INDEX = 0
    const val ADD_NEW_OR_CHANGE_CHILD_DEFAULT_VALUE_FINANCE = 0

    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_CHILD_ID = -1
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_CHILD_NAME = ""
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_COMING = "Проведено"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_NOT_COMING = "Отменено"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_SOON = "Назначенно"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_PAY_STATUS_PAID = "Оплачено"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_PAY_STATUS_NOT_PAID = "Не оплачено"
    val monthNames = mapOf(
        1 to "Январь",
        2 to "Февраль",
        3 to "Март",
        4 to "Апрель",
        5 to "Май",
        6 to "Июнь",
        7 to "Июль",
        8 to "Август",
        9 to "Сентябрь",
        10 to "Октябрь",
        11 to "Ноябрь",
        12 to "Декабрь"
    )
    const val DATE_HELPER_LANGUAGE = "ru"
    const val DATE_HELPER_DATE_FORMATER = "dd.MM.yyyy"
    const val DATE_HELPER_DATE_SECOND_FORMATER = "d.MM.yyyy"

}