package com.example.wizkids.presentation.ui.visitScreen.sharedVisitConstant

object SharedVisitLogicConstant {
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_CHILD_ID = -1
     val CREATE_A_NEW_VISIT_DEFAULT_VALUE_STATUS_LIST = listOf(
        PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_COMING,
        PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_NOT_COMING,
        PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_SOON
    )
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_NAME = ""
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_INFO = ""
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_PAY_STATUS = ""
    const val CREATE_A_NEW_VISIT_DEFAULT_VALUE_SELECTED_STATUS = ""
    const val ADD_VISIT_DEFAULT_VALUE_BY_ID = 1
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_COMING = "Пришёл"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_NOT_COMING = "Не пришёл"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_SOON = "Назначено"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_PAY_STATUS_PAID = "Оплачено"
    const val PERSONAL_VISIT_WINDOW_DEFAULT_VALUE_PAY_STATUS_NOT_PAID = "Не оплачено"


}