package com.example.wizkids.presentation.ui.sharedUI.constant

object SharedUiLogicConstant {
    val COMING_VISITS_INFORMATION_WINDOW_STATUS_LIST = listOf(
        COMING_STATUS_COMING,
        COMING_STATUS_NOT_COMING,
        COMING_STATUS_SOON
    )
    const val COMING_STATUS_COMING = "Пришёл"
    const val COMING_STATUS_NOT_COMING = "Не пришёл"
    const val COMING_STATUS_SOON = "Назначено"
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_STATUS_VISIT = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_NAME_VISIT = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_PAY_STATUS = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_INFO_VISIT = ""
    const val COMING_VISITS_INFORMATION_WINDOW_DEFAULT_VALUE_VISIT_DATE_COMING = ""
    const val COMING_VISITS_INFORMATION_WINDOW_INDEX_PLUS_VALUE = 1
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_NAME = ""
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DESCRIPTION = ""
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_SELECTED_IMAGE_INDEX = 0
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_SELECTED_IMAGE_MINUS_INDEX = 1
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DOCS_LIST_REMOVE_INDEX = 1
    const val DOCUMENT_INFORMATION_WINDOW_ADD_IMAGE_ICON_SIZE = 50
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_SPACER_HEIGHT = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_SIZE = 80
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_PADDING_HORIZONTAL = 4
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_CLIP = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_BOX_SIZE = 80
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_BOX_CLIP = 8
    const val DOCUMENT_INFORMATION_WINDOW_IMAGE_LIST_ITEM_ICON_ADD_NEW_IMAGE_SIZE = 30
    const val DOCUMENT_INFORMATION_WINDOW_SPACER_IMAGE_TO_DOCS_INFO_HEIGHT = 16
    const val DOCUMENT_INFORMATION_WINDOW_DEFAULT_VALUE_DOCS_LIST_ADD_INDEX = 1
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_DEBT = "Долг"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_PAY_SOON = "Оплата в след.визит"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_PAYED = "Оплачено"
    const val INFORMATION_IMAGE_AND_PAY_STATUS_STATUS_NOT_PAYED = "Не Оплачено"
    const val CHILD_CARD_INITIAL_FULL_NAME_INDEX = 2
    const val CHILD_CARD_INITIAL_PARTS_INDEX_FIRST_NAME = 0
    const val CHILD_CARD_INITIAL_PARTS_INDEX_LAST_NAME = 1
    const val CHILD_CARD_INITIAL_PARTS_INDEX_TAKE_INDEX = 2
    const val CHILD_CARD_DEFAULT_VALUE_PAY_STATUS = ""
    const val GET_DATE_TEXT_INPUT_DATE_FORMAT = "%02d.%02d.%d"
    const val HEADER_DEFAULT_VALUE_INFO_SELECTION = ""
    const val FOOTER_ITEM_DEFAULT_VALUE_PADDING_START = 1
    const val FOOTER_ITEM_DEFAULT_VALUE_PADDING_END = 3
    const val FOOTER_SELECTED_INDEX_DEFAULT_VALUE = 0
    const val TIME_HELPER_DEFAULT_VALUE_HOUR = 12
    const val TIME_HELPER_DEFAULT_VALUE_MINUTE = 0
    const val INFORMATION_INITIAL_FIRST_NAME_INDEX = 0
    const val INFORMATION_INITIAL_SECOND_NAME_INDEX = 0
    const val ADD_NEW_OR_CHANGE_CHILD_DEFAULT_VALUE_FINANCE = 0


}