package com.example.wizkids.presentation.main.constant

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object MainViewConstant {
    val FooterPaddingTop = 12.dp
    val FooterPaddingBottom = 20.dp
    val FooterPaddingStart = 25.dp
    val FooterWeight = 1f
    val FooterTextPadding = 12.dp
    val HeaderWeight = 1f
    val HeaderColumnPaddingStart = 24.dp
    val HeaderColumnPaddingTop = 50.dp
    val HeaderTextPaddingTop = 4.dp
    val HeaderTextPaddingBottom = 12.dp
    val WhiteTextFontSize = 14.sp
    val GrayTextFontSize = 14.sp
    val ItalyTextFontSize = 20.sp
    val ItalyTextLineHeight = 24.sp
    val BlueTextFontSize = 14.sp
    val WhiteSortedTextFontSize = 14.sp
    val AllChuildColumnHorizontalPadding = 12.dp
    val AllChuildRowClip = 8.dp
    val AllChuildRowPadding = 10.dp
    val AllChuildBoxSize = 12.dp
    val AllChuildBoxClip = 50.dp
    val AllChuildTextPadding = 8.dp
    val ChildCardColumnPaddingVertical = 12.dp
    val ChildCardColumnClip = 12.dp
    val ChildCardImageColumnPaddingStart = 12.dp
    val ChildCardImageBoxSize = 44.dp
    val ChildCardImageBoxClip = 50.dp
    val ChildCardImageTextSize = 12.sp
    val ChildCardColumnInfoWeight = 1f
    val ChildCardColumnInfoPadding = 12.dp
    val ChildCardColumnInfoItalyRextSize = 16.sp
    val ChildCardColumnPayInfoWeight = 1f
    val ChildCardColumnPayInfoPadding = 12.dp
    val ChildCardColumnPayInfoSizeWeight = 1f
    val ChildCardColumnPayInfoClip = 12.dp
    val ChildCardColumnPayInfoTextPaddingHorizontal = 12.dp
    val ChildCardColumnPayInfoTextPaddingVertical = 5.dp
    val ButtonAddNewChildBoxSize = 52.dp
    val ButtonAddNewChildBoxClip = 50.dp
    val MainActivityChildScreenWeight = 1f
    val ChildScreenPaddingHorizontal = 12.dp
    val FiltersColumnPaddingTop = 12.dp
    val FiltersOutlineTextFieldClip = 15.dp
    val FiltersOutlineTextFieldtextStyleSize = 14.sp
    val FiltersOutlineTextFieldShape = 12.dp
    val FiltersColumnWeight = 1f
    val FiltersColumnPadding = 12.dp
    val FiltersColumnClip = 20.dp
    val FiltersColumnTextPaddingVertical = 20.dp
    val WindowSortedItalyTextSize = 18.sp
    val WindowSortedSpacerHeight = 20.dp
    val WindowSortedOptionColumn = 12.dp
    val WindowSortedOptionSpacerHeight = 12.dp
    val WindowSortedButtonResetWeight = 1f
    val WindowSortedButtonResetPadding = 12.dp
    val WindowSortedButtonCancelWeight = 1f
    val WindowSortedButtonCancelPadding = 12.dp
    val OptionCardColumnClip = 12.dp
    val OptionCardColumnPadding = 12.dp
    val OptionCardBoxSize = 16.dp
    val OptionCardBoxBorderWidth = 2.dp
    val OptionCardBoxBorderShare = 50.dp
    val OptionCardBoxFillSize = 9.dp
    val OptionCardBoxFillClip = 50.dp
    val OptionCardWhiteTextPadding = 12.dp
    val WindowFiltersColumnGlobalPadding = 12.dp
    val WindowFiltersGlobalItalyTextSize = 18.sp
    val WindowFiltersSpacerHeight = 20.dp
    val WindowFiltersItalyTextSize = 16.sp
    val WindowFiltersRow= 10.dp
    val WindowFiltersRowOutlinedTextFieldWeight= 1f
    val WindowFiltersRowOutlinedTextFieldPadding= 2.dp
    val WindowFiltersRowOutlinedTextFieldTextStyleSize= 14.sp
    val WindowFiltersColumnPadding = 12.dp
    val WindowFiltersColumnRowPaddingTop = 10.dp
    val WindowFiltersColumnRowPadding = 2.dp
    val WindowFiltersColumnRowWeight = 1f
    val WindowFiltersColumnRowClip = 12.dp
    val WindowFiltersColumnRowPaddingHorizontal = 13.dp
    val WindowFiltersColumnRowPaddingVertical = 14.dp
    val WindowFiltersColumnRowIconSize = 20.dp
    val WindowFiltersColumnRowSpacerWidth = 12.dp
    val WindowFiltersExposedDropdownMenuBoxPadding = 10.dp
    val WindowFiltersButtonApplyWeight = 1f
    val WindowFiltersButtonApplyPadding = 12.dp
    val WindowFiltersButtonCancelWeight = 1f
    val WindowFiltersButtonCancelPadding = 12.dp
    val AddNewChildActivityNewChildScreenWeight = 1f

}