package com.example.wizkids.presentation.addNewOrChangeChild.constant

object AddNewOrChangeUserLogicConstant {
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_FULLNAME = ""
    const val ADD_NEW_OR_CHANGE_USER_INDEX_OF_FIRST_NAME = 1
    const val ADD_NEW_OR_CHANGE_USER_INDEX_OF_MIDDLE_NAME = 0
    const val ADD_NEW_OR_CHANGE_USER_INDEX_OF_LAST_NAME = 2
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_FIRST_NAME = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_LAST_NAME = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_MIDDLE_NAME = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_IMAGE = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_DATE_OF_BIRTH = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_ABOUT = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_WORK_EXPERIENCE = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_PHONE = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_EMAIL = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_EDUCATION_LEVEL = ""
    const val ADD_NEW_OR_CHANGE_USER_DEFAULT_VALUE_SPECIALIZATION = ""

}