package com.example.wizkids.presentation.main.constant

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object MainViewConstant {
    const val MAIN_ACTIVITY_MAIN_CONTAINER_WEIGHT = 1f
    const val MAIN_ACTIVITY_MAIN_CONTAINER_HORIZONTAL_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_MAIN_CONTAINER_TOP_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_ITALY_TEXT_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_COLUMN_CONTAINER_WEIGHT = 1f
    const val MAIN_ACTIVITY_MAIN_FILTERS_COLUMN_CONTAINER_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_COLUMN_CONTAINER_CLIP = 20
    const val MAIN_ACTIVITY_MAIN_FILTERS_COLUMN_TEXT_VERTICAL_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_SORTED_COLUMN_CONTAINER_WEIGHT = 1f
    const val MAIN_ACTIVITY_MAIN_SORTED_COLUMN_CONTAINER_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_SORTED_COLUMN_CONTAINER_CLIP = 20
    const val MAIN_ACTIVITY_MAIN_SORTED_COLUMN_TEXT_VERTICAL_PADDING = 12

    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_AGE_MAIN_CONTAINER_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_AGE_CONTAINER_LABEL_SIZE = 25
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_AGE_CONTAINER_SPACER_HEIGHT = 10
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_AGE_CONTAINER_SUBLABEL_SIZE = 25
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_AGE_HINT_CONTAINER_TOP_PADDING = 12


    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_PAY_STATUS_MAIN_CONTAINER_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_PAY_STATUS_CONTAINER_LABEL_SIZE = 25
    const val MAIN_ACTIVITY_MAIN_FILTERS_BY_PAY_STATUS_SELECTED_ITEM_SIZE = 14
    const val MAIN_ACTIVITY_MAIN_FILTERS_BUTTON_WEIGHT = 1f
    const val MAIN_ACTIVITY_MAIN_FILTERS_BUTTON_PADDING = 14

    const val MAIN_ACTIVITY_MAIN_SORTED_CONTAINER_LABEL_SIZE = 25
    const val MAIN_ACTIVITY_MAIN_SORTED_CONTAINER_SPACER_HEIGHT = 10
    const val MAIN_ACTIVITY_MAIN_SORTED_COLUMN_OPTION_PADDING = 10
    const val MAIN_ACTIVITY_MAIN_SORTED_OPTION_SPACER_HEIGHT = 10
    const val MAIN_ACTIVITY_MAIN_SORTED_BUTTON_WEIGHT = 1f
    const val MAIN_ACTIVITY_MAIN_SORTED_BUTTON_PADDING = 14
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_CLIP = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_PADDING = 20

    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_BOX_SIZE = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_BOX_WIDTH = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_BOX_SHAPE = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_BOX_BOX_SIZE = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_BOX_BOX_SHAPE = 20
    const val MAIN_ACTIVITY_MAIN_OPTION_CARD_TEXT_PADDING = 20

    const val MAIN_ACTIVITY_MAIN_ALL_CHILD_COLUMN_HORIZONTAL_PADDING = 12
    const val MAIN_ACTIVITY_MAIN_BUTTON_ADD_NEW_CHILD_BOX_SIZE = 50
    const val MAIN_ACTIVITY_MAIN_BUTTON_ADD_NEW_CHILD_BOX_CLIP = 50
    const val MAIN_ACTIVITY_MAIN_CHILD_STATE_CONTROLLER_SUCCESS_ROW_CLIP = 20
    const val MAIN_ACTIVITY_MAIN_CHILD_STATE_CONTROLLER_SUCCESS_ROW_PADDING = 20
    const val MAIN_ACTIVITY_MAIN_CHILD_STATE_CONTROLLER_SUCCESS_BOX_SIZE = 20
    const val MAIN_ACTIVITY_MAIN_CHILD_STATE_CONTROLLER_SUCCESS_BOX_CLIP = 20
    const val MAIN_ACTIVITY_MAIN_CHILD_STATE_CONTROLLER_SUCCESS_TEXT_PADDING = 12



}